//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarianWorkplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthHistory
    {
        public int idAuth { get; set; }
        public int idEmployee { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
