//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarianWorkplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string Name { get; set; }
        public string Author { get; set; }
        public int YearOfPublication { get; set; }
        public string InStock { get; set; }
        public int Count { get; set; }
        public int idBook { get; set; }
    }
}
